import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-hidden`}
      >
        <Navbar />
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}

{
  /* <div className="w-full h-75 absolute -bottom-90 -left-30 bg-primary/20 inset rounded-full blur-[480px]"></div>
          <div className="w-75 h-75 absolute -right-80 -top-90 bg-primary/20 inset rounded-full blur-[480px]"></div> */
}
